"""empty message

Revision ID: 482f7825591b
Revises: 1ae5390b28a1
Create Date: 2016-05-25 11:11:30.194030

"""

# revision identifiers, used by Alembic.
revision = '482f7825591b'
down_revision = '1ae5390b28a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
